skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrowq32026 = "BPgNv59HnR2Gm7BNvZ3MbM83FQxm2QKxsherrT16soQp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
